### ISSUE TITLE
\diagbox content generates division by zero error

### ISSUE THREAD

**Issue by FrankMittelbach** [leo-liu/tex-pkg#28]
commented out line generates the error

```
\documentclass{article}
\pagestyle{empty}

\usepackage{diagbox}

\begin{document}
\diagbox{column}{table}{row}     % ok
%%\diagbox{column}{table}{\\row} %                  <---- division by zero
\diagbox{column}{table}{\\[-6pt]row} % ok
\diagbox[width=3cm]{column}{table}{\\row}  % ok, but bad result without height= :-)

\begin{tabular}{|l|c|c|c|} \hline
\diagbox[width=3cm]{column}{table}{\\[-8pt]row}  
 & R1 & R2 & R3 \\
xxx &      & Y & \diagbox{A}{B} \\
\hline
\end{tabular}
\end{document}
```

**Comment by leo-liu** [comment]
I'll think it over later.
there might be a better algorithm to calculate the dimensions.

**Comment by FrankMittelbach** [comment]
Any outcome from the thinking? I would appreciate a fix, so that I can include your package in TLC

**Comment by leo-liu** [comment]
The problem is caused by the algorithm to calculate the width and height of diagbox.

In fact, the algorithm is straightforward, that solves equations from similar triangles.

![pic](https://user-images.githubusercontent.com/570611/74013412-5d3fc000-49c7-11ea-9017-3d1c8255eefd.png)

then we have:
(y - ym) / ya = x / (x - xa),
(x - xm) / xb = y / (y - yb).

We need to solve the quadric equations that x > xm + xb and y > ym + ya.
Unfortunately, when yb = ya + ym, the equation has no solution.

This algorithm is simple and intuitive, but not perfect. Maybe we can set some thresholds to prevent such exordinary data.

**Comment by FrankMittelbach** [comment]
I guess that could be caught couldn't it. Would be most likely better than a low-level division by error :-)

**Comment by leo-liu** [comment]
a new version of diagbox has been uploaded to CTAN

**Comment by FrankMittelbach** [comment]
my section in the book now runs through without errors, thanks for the updates
